import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['cyrillic'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  );
}
